# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Self Hosted Agents
name: ubuntu

steps:
- script: |
    az deployment group create --resource-group lielResourceGroup --template-file storageAccounts.json
  displayName: 'Deploy Storage Accounts'

- script: |
    az deployment group create --resource-group lielResourceGroup --template-file windowsServer2022.json --parameters windowsServer2022.parameters.json
  displayName: 'Deploy Windows Server'

  